In [24]:
import pandas as pd
import numpy as np
import sklearn.preprocessing
import sklearn.tree

In [25]:
dev = pd.read_csv("dev.csv")

In [26]:
test = pd.read_csv("test.csv")

In [27]:
val = pd.read_csv("val.csv")

In [28]:
train = pd.read_csv("train.csv")

In [29]:
train.head()

,group,KV37,LV469,LV861,LVX54,LV746,LV218,LV316,LV312,LV310,...,ARMD4,C1QT5,B2L12,PLXA4,B3GN2,PCDGL,AGRB1,RECK,PSA1,F174A
0,Healthy,28.398290,23.968009,24.296234,21.073690,24.306090,20.834275,22.875021,21.873272,22.012922,...,18.424523,19.702409,28.571054,17.582277,19.833578,17.908683,21.082685,19.540313,20.402270,24.200471
1,Healthy,28.493880,21.512320,22.687815,22.182946,24.306486,23.766681,22.963114,22.786492,22.369101,...,17.826979,19.526250,27.953139,18.670746,18.612532,19.756105,21.337060,19.896682,20.481528,24.270255
2,Healthy,28.860446,22.780248,24.378107,23.365133,25.866827,22.743360,23.808291,22.685879,22.985000,...,18.153627,20.114505,27.944534,18.229467,19.640964,18.612921,21.079712,19.559118,20.400989,24.200733
3,Healthy,28.780151,22.422778,22.902736,21.364631,25.018863,24.221923,23.466170,22.392122,21.878784,...,14.228847,20.311589,28.000618,17.943092,20.497359,19.247203,21.691704,20.267159,20.199615,24.667232
4,Healthy,28.277717,24.656308,24.440401,22.411287,26.695574,26.185975,24.878200,23.932789,24.279117,...,16.580325,19.468810,28.342385,17.563858,19.788633,18.069438,21.078241,19.565659,20.400481,24.200606

In [30]:
train_cols = train.loc[:, train.columns != 'group']
train_cols.head()

,KV37,LV469,LV861,LVX54,LV746,LV218,LV316,LV312,LV310,LV39,...,ARMD4,C1QT5,B2L12,PLXA4,B3GN2,PCDGL,AGRB1,RECK,PSA1,F174A
0,28.398290,23.968009,24.296234,21.073690,24.306090,20.834275,22.875021,21.873272,22.012922,23.189925,...,18.424523,19.702409,28.571054,17.582277,19.833578,17.908683,21.082685,19.540313,20.402270,24.200471
1,28.493880,21.512320,22.687815,22.182946,24.306486,23.766681,22.963114,22.786492,22.369101,23.807096,...,17.826979,19.526250,27.953139,18.670746,18.612532,19.756105,21.337060,19.896682,20.481528,24.270255
2,28.860446,22.780248,24.378107,23.365133,25.866827,22.743360,23.808291,22.685879,22.985000,23.899330,...,18.153627,20.114505,27.944534,18.229467,19.640964,18.612921,21.079712,19.559118,20.400989,24.200733
3,28.780151,22.422778,22.902736,21.364631,25.018863,24.221923,23.466170,22.392122,21.878784,24.092134,...,14.228847,20.311589,28.000618,17.943092,20.497359,19.247203,21.691704,20.267159,20.199615,24.667232
4,28.277717,24.656308,24.440401,22.411287,26.695574,26.185975,24.878200,23.932789,24.279117,25.183091,...,16.580325,19.468810,28.342385,17.563858,19.788633,18.069438,21.078241,19.565659,20.400481,24.200606

In [31]:
val_cols = val.loc[:, val.columns != 'group']
val_cols.head()

,KV37,LV469,LV861,LVX54,LV746,LV218,LV316,LV312,LV310,LV39,...,ARMD4,C1QT5,B2L12,PLXA4,B3GN2,PCDGL,AGRB1,RECK,PSA1,F174A
0,28.296151,22.771117,22.632904,18.940923,26.030090,22.936320,23.606448,22.799581,22.903295,24.048560,...,18.804976,20.020770,28.235481,18.083343,18.092063,18.517482,21.069978,19.580428,20.398639,24.197844
1,29.977636,23.888451,25.216371,21.298754,25.562505,24.143215,23.698001,22.515224,22.892529,24.433092,...,18.135083,19.666451,27.931620,17.678088,19.836151,17.958065,21.100102,19.350755,20.449790,24.181823
2,29.128515,24.008177,23.316941,23.360000,25.722765,20.547587,23.590429,22.477097,23.073474,23.757367,...,17.963519,19.625770,27.723883,18.623098,19.822466,17.936343,21.073721,19.576590,20.399343,24.199361
3,28.680616,22.788686,22.386033,17.379360,25.442586,24.331978,23.444374,22.621024,22.876718,24.207290,...,19.578058,19.896841,27.984952,19.521932,20.190895,18.937455,21.700087,19.981205,20.581440,23.922892
4,29.686497,23.769176,23.217372,23.161013,26.900271,24.877180,23.715628,22.994822,23.115394,24.720236,...,17.478294,19.499470,28.015216,18.944578,20.083677,17.917691,21.044841,19.774079,20.668239,24.074973

In [41]:
train_X = train_cols.values
val_X = val_cols.values

train_y_regr = train['group'].values.reshape(-1,1)
val_y_regr = val['group'].values.reshape(-1,1)

In [42]:
scaler = sklearn.preprocessing.StandardScaler()
train_X = scaler.fit_transform(train_X)
val_X = scaler.transform(val_X)

In [43]:
clf = sklearn.tree.DecisionTreeClassifier()

clf = clf.fit(train_X, train_y_regr)

y_pred = clf.predict(val_X)

In [44]:
print("Accuracy:", sklearn.metrics.accuracy_score(val_y_regr, y_pred))

Accuracy: 0.5833333333333334